name: Build

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Enable to be called for redeployment
  workflow_call:
    secrets:
      token:
        required: true

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  # Single deploy job since we're just deploying
  build:
    if: github.event.head_commit.author.email != 'actions@github.com'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ env.GH_TOKEN }}

      - name: Checkout registered events
        uses: actions/checkout@v4
        with:
          ref: register_events
          path: reg

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install dependencies in register_events branch
        working-directory: reg
        run: npm ci

      - name: Register events
        working-directory: reg
        run: |
          npm start -- ./registered_events.yaml ../src/data/registered_events.ts

      # This is already enough for Github pages, however...
      # Must check-in changes for Cloudflar pages to pickup the latest files updated
      - name: Check-in main
        run: |
          rm -rf reg
          if [ -n "$(git status --porcelain)" ]; then
          # Check if there are any changes (-n = means non-zero length; -z = means zero-length)
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"

            git add -A
            git commit -m "🤖 Register events"
            git push
          else
            echo "No changes to commit."
          fi

      # Cloudflare has a separate deployment build
      # Github pages is removed
