# Simple workflow for deploying static content to GitHub Pages
name: Deployment of static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Enable to be called for redeployment
  workflow_call:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    if: github.event.head_commit.author.email != 'actions@github.com'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Checkout registered events
        uses: actions/checkout@v4
        with:
          ref: register_events
          path: reg

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install dependencies in register_events branch
        working-directory: reg
        run: npm ci

      - name: Register events
        working-directory: reg
        run: |
          npm start -- ./registered_events.yaml ../src/data/registered_events.ts

      # This is already enough for Github pages, however...
      # Must check-in changes for Cloudflar pages to pickup the latest files updated
      - name: Check-in main
        run: |
          if [ -n "$(git status --porcelain)" ]; then
          # Check if there are any changes (-n = means non-zero length; -z = means zero-length)
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"

            git add -A
            git commit -m "🤖 Register events"
            git push
          else
            echo "No changes to commit."
          fi

      - name: Build
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload dist folder
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
