name: Redeploy

on:
  push:
    branches: register_events
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  redeploy:
    if: github.event.head_commit.author.email != 'actions@github.com'
    uses: lightzane/sky-events/.github/workflows/ci.yaml@main
