name: Register Events

on:
  # Runs on pushes targeting the default branch
  push:
    branches: register_events

jobs:
  # Single deploy job since we're just deploying
  register:
    runs-on: ubuntu-latest
    if: github.event.head_commit.author.email != 'actions@github.com'
    steps:
      - name: Checkout this branch
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          path: main

      - name: Test
        run: |
          echo "Check main"
          ls main
          echo "Check reg"
          ls

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Read registration yaml
        run: |
          yq -o=json '.events' registration.yaml

      - name: Validate registration
        run: |
          # Load the YAML file and check for null names
          if yq e '.events[] | select(.[] == null)' registration.yaml | grep -q .; then
            echo "Error: One or more items have a null field"
            echo "If the field is optional, then either remove the field completely or provide value"
            exit 1
          else
            echo "All events have valid names."
          fi

          # select(.name == null) filters out only those items where the name is null.
          # select(.[] == null) filters out only those items where any field is null.

          # The grep -q . checks if there is any output from the previous command. 
          # If there is, it means at least one item has a null name.

      - name: Register events
        run: |
          yq e '.events += load("registration.yaml").events' -i registered_events.yaml

      - name: Get Current Date
        run: |
          current_date=$(date +"%d-%b-%Y" | tr '[:lower:]' '[:upper:]')

          # %d = Day of month (01 to 31)
          # %b = Abbreviated month name (Jan to Dec)
          # %Y = Year in four digits

          # | tr '[:lower:]' '[:upper:]'
          # This pipes the output to tr, which translates lowercase letters to uppercase,
          # converting the month abbreviation from Oct to OCT.

          # Example Output: 
          # 04-OCT-2024

          # N=10  # Replace 10 with the number of days you want to add
          # date -d "+$N days" +"%d-%b-%Y" | tr '[:lower:]' '[:upper:]'

          echo CURRENT_DATE=$current_date >> $GITHUB_ENV

      - name: Cleanup
        run: |
          echo "Today is $CURRENT_DATE"

          # Update template.yaml
          yq e ".events[0].start = \"$CURRENT_DATE\"" -i template.yaml
          yq e ".events[0].end = \"$CURRENT_DATE\"" -i template.yaml

          # yq e = executes the expression
          # -i = edits the file in place

          rm registration.yaml && cp template.yaml registration.yaml

      - name: Check-in
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add template.yaml registration.yaml
          git commit -m "🤖 Cleanup"
          git push

  redeploy:
    needs: register
    runs-on: ubuntu-latest
    steps:
      - name: Run it
        run: echo "Success"
